import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import LoginForm from './components/login-form'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Es Jeruk Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid h-screen place-items-center">
          <div className="card lg:card-side bg-base-100 shadow-xl max-w-2xl max-h-100">
            <div className='basis-1/2'>
            <figure>
              <img
                src="https://www.splashlearn.com/math-vocabulary/wp-content/uploads/2022/05/image5-888x1024.jpg"
                className="max-h-fit rounded-l-lg"
                alt="Album"
              />
            </figure>
            </div>
            <div className="card-body">
              <LoginForm/>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
